import pandas as pd
import pymem

pm = pymem.Pymem('MonsterHunterWorld.exe')

base_offset = 0x5013950
slot_offset = 0x26CC00
monster_offset = 0xF4EA8
weapon_offset = 0x148CB4
endemic_life_offset = 0xF6F28

base_address = pm.base_address + base_offset

slot = 1
gSave = 0
gSaveMon = 0
gSaveWeap = 0
svData = 0

rcx = pm.read_longlong(base_address)
rcx = pm.read_longlong(rcx + 0xA8)
rdx = slot_offset * (slot - 1)
rcx += rdx

gSave = rcx
gSaveMon = rcx + monster_offset
gSaveWeap = rcx + weapon_offset
svData = rcx + endemic_life_offset

data = {}


def read_pointer_var(var: str, base_address: int, offsets: list[int], var_type: str, length: int = 100):
	address = base_address

	for offset in offsets[:-1]:
		address = pm.read_ulonglong(address + offset)

	final_address = address + offsets[-1]

	match var_type:
		case 'int':
			value = pm.read_int(final_address)
		case 'float':
			value = pm.read_float(final_address)
		case 'double':
			value = pm.read_double(final_address)
		case 'bool':
			value = pm.read_bool(final_address)
		case 'long':
			value = pm.read_long(final_address)
		case 'longlong':
			value = pm.read_longlong(final_address)
		case 'string':
			value = pm.read_string(final_address, length)
		case 'binary':
			if not 0 <= length <= 7:
				raise ValueError("Bit index for 'binary' must be between 0 and 7.")
			byte_value = pm.read_bytes(final_address, 1)
			value = byte_value[0] >> length & 1
		case _:
			raise ValueError(f"Unsupported variable type: {var_type}")

	data.update({var: value})


pointers = [
	('Hunter Name', gSave, [0x50], 'string', 16),
	('Hunter Rank', gSave, [0x90], 'int'),
	('Zenny', gSave, [0x94], 'int'),
	('Research Points', gSave, [0x98], 'int'),
	('Hunter Rank Experience', gSave, [0x9C], 'int'),
	('Play Time (s)', gSave, [0xA0], 'int'),
	('Master Rank', gSave, [0xD4], 'int'),
	('Master Rank Experience', gSave, [0xD8], 'int'),
	('Palico Name', gSave, [0x10261C], 'string', 16),
	('Palico Experience', gSave, [0x10265C], 'int'),
	('Palico Gadget Proficiency - Vigorwasp Spray', gSave, [0x102660], 'int'),
	('Palico Gadget Proficiency - Flashfly Cage', gSave, [0x102664], 'int'),
	('Palico Gadget Proficiency - Shieldspire', gSave, [0x102668], 'int'),
	('Palico Gadget Proficiency - Coral Orchestra', gSave, [0x10266C], 'int'),
	('Palico Gadget Proficiency - Plunderblade', gSave, [0x102670], 'int'),
	('Palico Gadget Proficiency - Meowlotov Cocktail', gSave, [0x102674], 'int'),
	('Palico Tailraiders Unity - Bugtrappers', gSave, [0x1026A0], 'int'),
	('Palico Tailraiders Unity - Protectors', gSave, [0x1026A4], 'int'),
	('Palico Tailraiders Unity - Troupers', gSave, [0x1026A8], 'int'),
	('Palico Tailraiders Unity - Plunderers', gSave, [0x1026AC], 'int'),
	('Palico Tailraiders Unity - Gajalaka', gSave, [0x1026B0], 'int'),
	('Palico Tailraiders Unity - Boaboa', gSave, [0x1026BC], 'int'),
	('Unity', gSave, [0x16E248], 'int'),
	('Achievements - Conqueror of the New World', gSave, [0x148460], 'binary', 0),
	('Achievements - Welcome to the New World', gSave, [0x148460], 'binary', 1),
	('Achievements - Nothing Stops This Commission', gSave, [0x148460], 'binary', 2),
	('Achievements - Defender of Astera', gSave, [0x148460], 'binary', 3),
	('Achievements - Into the Deep', gSave, [0x148460], 'binary', 4),
	('Achievements - Death Begets Life', gSave, [0x148460], 'binary', 5),
	('Achievements - The Empress of the Highlands', gSave, [0x148460], 'binary', 6),
	('Achievements - One Shall Stand, One Shall Fall', gSave, [0x148460], 'binary', 7),
	('Achievements - The Sapphire Star', gSave, [0x148461], 'binary', 0),
	('Achievements - The Hunters Life for Me', gSave, [0x148461], 'binary', 1),
	('Achievements - An Inquisitive Mind', gSave, [0x148461], 'binary', 2),
	('Achievements - The Franchise Hunter', gSave, [0x148461], 'binary', 3),
	('Achievements - Step into the Arena', gSave, [0x148461], 'binary', 4),
	('Achievements - Nowhere to Go but Up', gSave, [0x148461], 'binary', 5),
	('Achievements - New World Settler', gSave, [0x148461], 'binary', 6),
	('Achievements - The Art of Camouflage', gSave, [0x148461], 'binary', 7),
	('Achievements - Angling for a Bite', gSave, [0x148462], 'binary', 0),
	('Achievements - Mmm, So Tasty!', gSave, [0x148462], 'binary', 1),
	('Achievements - The Bigger They Are...', gSave, [0x148462], 'binary', 2),
	('Achievements - A Living Fossil', gSave, [0x148462], 'binary', 3),
	('Achievements - Snuggles for All', gSave, [0x148462], 'binary', 4),
	('Achievements - Bristles for All', gSave, [0x148462], 'binary', 5),
	('Achievements - Rainbow Bright', gSave, [0x148462], 'binary', 6),
	('Achievements - Commissioned Work', gSave, [0x148462], 'binary', 7),
	('Achievements - Bourgeois Hunter', gSave, [0x148463], 'binary', 0),
	('Achievements - Impregnable Defense', gSave, [0x148463], 'binary', 1),
	('Achievements - Power is Everything', gSave, [0x148463], 'binary', 2),
	('Achievements - Movin On Up', gSave, [0x148463], 'binary', 3),
	('Achievements - First Friends', gSave, [0x148463], 'binary', 4),
	('Achievements - Bosom Buddies', gSave, [0x148463], 'binary', 5),
	('Achievements - Monster Ph.D.', gSave, [0x148463], 'binary', 6),
	('Achievements - Temper Temper', gSave, [0x148463], 'binary', 7),
	('Achievements - Indomitable', gSave, [0x148464], 'binary', 0),
	('Achievements - Miniature Crown', gSave, [0x148464], 'binary', 1),
	('Achievements - Miniature Crown Collector', gSave, [0x148464], 'binary', 2),
	('Achievements - Miniature Crown Master', gSave, [0x148464], 'binary', 3),
	('Achievements - Giant Crown', gSave, [0x148464], 'binary', 4),
	('Achievements - Giant Crown Collector', gSave, [0x148464], 'binary', 5),
	('Achievements - Giant Crown Master', gSave, [0x148464], 'binary', 6),
	('Achievements - Capture Novice', gSave, [0x148464], 'binary', 7),
	('Achievements - Capture Pro', gSave, [0x148465], 'binary', 0),
	('Achievements - Elderslayer', gSave, [0x148465], 'binary', 1),
	('Achievements - Monster Slayer', gSave, [0x148465], 'binary', 2),
	('Achievements - Monster Hunter', gSave, [0x148465], 'binary', 3),
	('Achievements - HELP!', gSave, [0x148465], 'binary', 4),
	('Achievements - I Am the Reinforcements', gSave, [0x148465], 'binary', 5),
	('Achievements - Hunters United', gSave, [0x148465], 'binary', 6),
	('Achievements - Hunters United Forever', gSave, [0x148465], 'binary', 7),
	('Achievements - Spreading the Word', gSave, [0x148466], 'binary', 0),
	('Achievements - Established Hunter', gSave, [0x148466], 'binary', 1),
	('Achievements - Conqueror of the Hinterlands', gSave, [0x148466], 'binary', 2),
	('Achievements - The Beginning of a New Expedition', gSave, [0x148466], 'binary', 3),
	('Achievements - Time to Get Serious', gSave, [0x148466], 'binary', 4),
	('Achievements - The Elusive Elder Dragon', gSave, [0x148466], 'binary', 5),
	('Achievements - Indomitable Spirit', gSave, [0x148466], 'binary', 6),
	('Achievements - The Old Everwyrm', gSave, [0x148466], 'binary', 7),
	('Achievements - An End and a Beginning', gSave, [0x148467], 'binary', 0),
	('Achievements - To the Land of Discoveries', gSave, [0x148467], 'binary', 1),
	('Achievements - Evolving Ecology', gSave, [0x148467], 'binary', 2),
	('Achievements - In Search of Rare Materials', gSave, [0x148467], 'binary', 3),
	('Achievements - Insatiable Investigator', gSave, [0x148467], 'binary', 4),
	('Achievements - Fate\'s Conclusion', gSave, [0x148467], 'binary', 5),
	('Achievements - Master Explorer', gSave, [0x148467], 'binary', 6),
	('Achievements - Source of Relaxation', gSave, [0x148467], 'binary', 7),
	('Achievements - Clutch Claw Neophyte', gSave, [0x148468], 'binary', 0),
	('Achievements - Golden Gleam', gSave, [0x148468], 'binary', 1),
	('Achievements - Friendly Pointer', gSave, [0x148468], 'binary', 2),
	('Achievements - Sweet Melody', gSave, [0x148468], 'binary', 3),
	('Achievements - Submerged Mystery', gSave, [0x148468], 'binary', 4),
	('Achievements - Celestial Illusion', gSave, [0x148468], 'binary', 5),
	('Achievements - Deft Digger', gSave, [0x148468], 'binary', 6),
	('Achievements - Creatures of the Earth', gSave, [0x148468], 'binary', 7),
	('Achievements - Unwavering Defense', gSave, [0x148469], 'binary', 0),
	('Achievements - Devastating Offense', gSave, [0x148469], 'binary', 1),
	('Achievements - Personal Treasure', gSave, [0x148469], 'binary', 2),
	('Achievements - First Ride', gSave, [0x148469], 'binary', 3),
	('Achievements - Experienced Rider', gSave, [0x148469], 'binary', 4),
	('Achievements - Fledgling Collector', gSave, [0x148469], 'binary', 5),
	('Achievements - Veteran Collector', gSave, [0x148469], 'binary', 6),
	('Achievements - Ultimate Collector', gSave, [0x148469], 'binary', 7),
	('Achievements - Remodeler', gSave, [0x14846A], 'binary', 0),
	('Achievements - Interior Decorator', gSave, [0x14846A], 'binary', 1),
	('Achievements - Architectural Artist', gSave, [0x14846A], 'binary', 2),
	('Achievements - Eager Engineer', gSave, [0x14846A], 'binary', 3),
	('Achievements - Skilled Steamworker', gSave, [0x14846A], 'binary', 4),
	('Achievements - Another Miniature Crown', gSave, [0x14846A], 'binary', 5),
	('Achievements - Another Giant Crown', gSave, [0x14846A], 'binary', 6),
	('Achievements - Fledgling Observer', gSave, [0x14846A], 'binary', 7),
	('Achievements - Outstanding Observer', gSave, [0x14846B], 'binary', 0),
	('Achievements - Helpful Hunter', gSave, [0x14846B], 'binary', 1),
	('Achievements - Master of Masters', gSave, [0x14846B], 'binary', 2),
	('Achievements - Monster Master', gSave, [0x14846B], 'binary', 3),
	('Achievements - True Miniature Crown Collector', gSave, [0x14846B], 'binary', 4),
	('Achievements - True Large Crown Collector', gSave, [0x14846B], 'binary', 5),
	('Achievements - The True Hunt Begins', gSave, [0x14846B], 'binary', 6),
	('Achievements - Hunter Prodigy', gSave, [0x14846B], 'binary', 7),
	('Achievements - Master Capturer', gSave, [0x14846C], 'binary', 0),
	('Achievements - Master Slayer', gSave, [0x14846C], 'binary', 1),
	('Achievements - Confronting the Unknown', gSave, [0x14846C], 'binary', 2),
	('Achievements - Seen It All', gSave, [0x14846C], 'binary', 3),
	('Quests Completed - Type - Investigations', gSave, [0x14848C], 'int'),
	('Quests Completed - Type - Arena Quests', gSave, [0x148490], 'int'),
	('Quests Completed - Type - High Rank Quests', gSave, [0x1484A0], 'int'),
	('Quests Completed - Type - Low Rank Quests', gSave, [0x1484A4], 'int'),
	('Quests Completed - Type - Master Rank Quests', gSave, [0x1484AC], 'int'),
	('Quests Completed - Type - Guiding Lands Quests', gSave, [0x1484B0], 'int'),
	('Time Spent in the Guiding Lands (s)', gSave, [0x16E278], 'int'),
	('Quests Completed in the Guiding Lands', gSave, [0x16E27C], 'int'),
	('Special Tracks Analyzed', gSave, [0x16E280], 'int'),
	('Hunting Log - Captured - Anjanath', gSaveMon, [0x0], 'int'),
	('Hunting Log - Captured - Rathalos', gSaveMon, [0x4], 'int'),
	('Hunting Log - Captured - Aptonoth', gSaveMon, [0x8], 'int'),
	('Hunting Log - Captured - Jagras', gSaveMon, [0xC], 'int'),
	('Hunting Log - Captured - Zorah Magdaros', gSaveMon, [0x10], 'int'),
	('Hunting Log - Captured - Mosswine', gSaveMon, [0x14], 'int'),
	('Hunting Log - Captured - Gajau', gSaveMon, [0x18], 'int'),
	('Hunting Log - Captured - Great Jagras', gSaveMon, [0x1C], 'int'),
	('Hunting Log - Captured - Kestodon (male)', gSaveMon, [0x20], 'int'),
	('Hunting Log - Captured - Rathian', gSaveMon, [0x24], 'int'),
	('Hunting Log - Captured - Pink Rathian', gSaveMon, [0x28], 'int'),
	('Hunting Log - Captured - Azure Rathalos', gSaveMon, [0x2C], 'int'),
	('Hunting Log - Captured - Diablos', gSaveMon, [0x30], 'int'),
	('Hunting Log - Captured - Black Diablos', gSaveMon, [0x34], 'int'),
	('Hunting Log - Captured - Kirin', gSaveMon, [0x38], 'int'),
	('Hunting Log - Captured - Behemoth', gSaveMon, [0x3C], 'int'),
	('Hunting Log - Captured - Kushala Daora', gSaveMon, [0x40], 'int'),
	('Hunting Log - Captured - Lunastra', gSaveMon, [0x44], 'int'),
	('Hunting Log - Captured - Teostra', gSaveMon, [0x48], 'int'),
	('Hunting Log - Captured - Lavasioth', gSaveMon, [0x4C], 'int'),
	('Hunting Log - Captured - Deviljho', gSaveMon, [0x50], 'int'),
	('Hunting Log - Captured - Barroth', gSaveMon, [0x54], 'int'),
	('Hunting Log - Captured - Uragaan', gSaveMon, [0x58], 'int'),
	('Hunting Log - Captured - Leshen', gSaveMon, [0x5C], 'int'),
	('Hunting Log - Captured - Pukei-Pukei', gSaveMon, [0x60], 'int'),
	('Hunting Log - Captured - Nergigante', gSaveMon, [0x64], 'int'),
	('Hunting Log - Captured - Xeno\'jiiva', gSaveMon, [0x68], 'int'),
	('Hunting Log - Captured - Kulu-Ya-Ku', gSaveMon, [0x6C], 'int'),
	('Hunting Log - Captured - Tzitzi-Ya-Ku', gSaveMon, [0x70], 'int'),
	('Hunting Log - Captured - Jyuratodus', gSaveMon, [0x74], 'int'),
	('Hunting Log - Captured - Tobi-Kadachi', gSaveMon, [0x78], 'int'),
	('Hunting Log - Captured - Paolumu', gSaveMon, [0x7C], 'int'),
	('Hunting Log - Captured - Legiana', gSaveMon, [0x80], 'int'),
	('Hunting Log - Captured - Great Girros', gSaveMon, [0x84], 'int'),
	('Hunting Log - Captured - Odogaron', gSaveMon, [0x88], 'int'),
	('Hunting Log - Captured - Radobaan', gSaveMon, [0x8C], 'int'),
	('Hunting Log - Captured - Vaal Hazak', gSaveMon, [0x90], 'int'),
	('Hunting Log - Captured - Dodogama', gSaveMon, [0x94], 'int'),
	('Hunting Log - Captured - Kulve Taroth', gSaveMon, [0x98], 'int'),
	('Hunting Log - Captured - Bazelgeuse', gSaveMon, [0x9C], 'int'),
	('Hunting Log - Captured - Apceros', gSaveMon, [0xA0], 'int'),
	('Hunting Log - Captured - Kelbi (male)', gSaveMon, [0xA4], 'int'),
	('Hunting Log - Captured - Kelbi (female)', gSaveMon, [0xA8], 'int'),
	('Hunting Log - Captured - Hornetaur', gSaveMon, [0xAC], 'int'),
	('Hunting Log - Captured - Vespoid', gSaveMon, [0xB0], 'int'),
	('Hunting Log - Captured - Mernos', gSaveMon, [0xB4], 'int'),
	('Hunting Log - Captured - Kestodon (female)', gSaveMon, [0xB8], 'int'),
	('Hunting Log - Captured - Raphinos', gSaveMon, [0xBC], 'int'),
	('Hunting Log - Captured - Shamos', gSaveMon, [0xC0], 'int'),
	('Hunting Log - Captured - Barnos', gSaveMon, [0xC4], 'int'),
	('Hunting Log - Captured - Girros', gSaveMon, [0xC8], 'int'),
	('Hunting Log - Captured - Ancient Leshen', gSaveMon, [0xCC], 'int'),
	('Hunting Log - Captured - Gastodon', gSaveMon, [0xD0], 'int'),
	('Hunting Log - Captured - Noios', gSaveMon, [0xD4], 'int'),
	('Hunting Log - Captured - Gajalaka', gSaveMon, [0xE0], 'int'),
	('Hunting Log - Captured - Tigrex', gSaveMon, [0xF4], 'int'),
	('Hunting Log - Captured - Nargacuga', gSaveMon, [0xF8], 'int'),
	('Hunting Log - Captured - Barioth', gSaveMon, [0xFC], 'int'),
	('Hunting Log - Captured - Savage Deviljho', gSaveMon, [0x100], 'int'),
	('Hunting Log - Captured - Brachydios', gSaveMon, [0x104], 'int'),
	('Hunting Log - Captured - Glavenus', gSaveMon, [0x108], 'int'),
	('Hunting Log - Captured - Acidic Glavenus', gSaveMon, [0x10C], 'int'),
	('Hunting Log - Captured - Fulgur Anjanath', gSaveMon, [0x110], 'int'),
	('Hunting Log - Captured - Coral Pukei-Pukei', gSaveMon, [0x114], 'int'),
	('Hunting Log - Captured - Ruiner Nergigante', gSaveMon, [0x118], 'int'),
	('Hunting Log - Captured - Viper Tobi-Kadachi', gSaveMon, [0x11C], 'int'),
	('Hunting Log - Captured - Nightshade Paolumu', gSaveMon, [0x120], 'int'),
	('Hunting Log - Captured - Shrieking Legiana', gSaveMon, [0x124], 'int'),
	('Hunting Log - Captured - Ebony Odogaron', gSaveMon, [0x128], 'int'),
	('Hunting Log - Captured - Blackveil Vaal Hazak', gSaveMon, [0x12C], 'int'),
	('Hunting Log - Captured - Seething Bazelgeuse', gSaveMon, [0x130], 'int'),
	('Hunting Log - Captured - Beotodus', gSaveMon, [0x134], 'int'),
	('Hunting Log - Captured - Banbaro', gSaveMon, [0x138], 'int'),
	('Hunting Log - Captured - Velkhana', gSaveMon, [0x13C], 'int'),
	('Hunting Log - Captured - Namielle', gSaveMon, [0x140], 'int'),
	('Hunting Log - Captured - Shara Ishvalda', gSaveMon, [0x144], 'int'),
	('Hunting Log - Captured - Popo', gSaveMon, [0x148], 'int'),
	('Hunting Log - Captured - Anteka', gSaveMon, [0x14C], 'int'),
	('Hunting Log - Captured - Wulg', gSaveMon, [0x150], 'int'),
	('Hunting Log - Captured - Cortos', gSaveMon, [0x154], 'int'),
	('Hunting Log - Captured - Boaboa', gSaveMon, [0x158], 'int'),
	('Hunting Log - Captured - Alatreon', gSaveMon, [0x15C], 'int'),
	('Hunting Log - Captured - Gold Rathian', gSaveMon, [0x160], 'int'),
	('Hunting Log - Captured - Silver Rathalos', gSaveMon, [0x164], 'int'),
	('Hunting Log - Captured - Yian Garuga', gSaveMon, [0x168], 'int'),
	('Hunting Log - Captured - Rajang', gSaveMon, [0x16C], 'int'),
	('Hunting Log - Captured - Furious Rajang', gSaveMon, [0x170], 'int'),
	('Hunting Log - Captured - Brute Tigrex', gSaveMon, [0x174], 'int'),
	('Hunting Log - Captured - Zinogre', gSaveMon, [0x178], 'int'),
	('Hunting Log - Captured - Stygian Zinogre', gSaveMon, [0x17C], 'int'),
	('Hunting Log - Captured - Raging Brachydios', gSaveMon, [0x180], 'int'),
	('Hunting Log - Captured - Safi\'jiiva', gSaveMon, [0x184], 'int'),
	('Hunting Log - Captured - Scarred Yian Garuga', gSaveMon, [0x18C], 'int'),
	('Hunting Log - Captured - Frostfang Barioth', gSaveMon, [0x190], 'int'),
	('Hunting Log - Captured - Fatalis', gSaveMon, [0x194], 'int'),
	('Hunting Log - Slain - Anjanath', gSaveMon, [0x200], 'int'),
	('Hunting Log - Slain - Rathalos', gSaveMon, [0x204], 'int'),
	('Hunting Log - Slain - Aptonoth', gSaveMon, [0x208], 'int'),
	('Hunting Log - Slain - Jagras', gSaveMon, [0x20C], 'int'),
	('Hunting Log - Slain - Zorah Magdaros', gSaveMon, [0x210], 'int'),
	('Hunting Log - Slain - Mosswine', gSaveMon, [0x214], 'int'),
	('Hunting Log - Slain - Gajau', gSaveMon, [0x218], 'int'),
	('Hunting Log - Slain - Great Jagras', gSaveMon, [0x21C], 'int'),
	('Hunting Log - Slain - Kestodon (male)', gSaveMon, [0x220], 'int'),
	('Hunting Log - Slain - Rathian', gSaveMon, [0x224], 'int'),
	('Hunting Log - Slain - Pink Rathian', gSaveMon, [0x228], 'int'),
	('Hunting Log - Slain - Azure Rathalos', gSaveMon, [0x22C], 'int'),
	('Hunting Log - Slain - Diablos', gSaveMon, [0x230], 'int'),
	('Hunting Log - Slain - Black Diablos', gSaveMon, [0x234], 'int'),
	('Hunting Log - Slain - Kirin', gSaveMon, [0x238], 'int'),
	('Hunting Log - Slain - Behemoth', gSaveMon, [0x23C], 'int'),
	('Hunting Log - Slain - Kushala Daora', gSaveMon, [0x240], 'int'),
	('Hunting Log - Slain - Lunastra', gSaveMon, [0x244], 'int'),
	('Hunting Log - Slain - Teostra', gSaveMon, [0x248], 'int'),
	('Hunting Log - Slain - Lavasioth', gSaveMon, [0x24C], 'int'),
	('Hunting Log - Slain - Deviljho', gSaveMon, [0x250], 'int'),
	('Hunting Log - Slain - Barroth', gSaveMon, [0x254], 'int'),
	('Hunting Log - Slain - Uragaan', gSaveMon, [0x258], 'int'),
	('Hunting Log - Slain - Leshen', gSaveMon, [0x25C], 'int'),
	('Hunting Log - Slain - Pukei-Pukei', gSaveMon, [0x260], 'int'),
	('Hunting Log - Slain - Nergigante', gSaveMon, [0x264], 'int'),
	('Hunting Log - Slain - Xeno\'jiiva', gSaveMon, [0x268], 'int'),
	('Hunting Log - Slain - Kulu-Ya-Ku', gSaveMon, [0x26C], 'int'),
	('Hunting Log - Slain - Tzitzi-Ya-Ku', gSaveMon, [0x270], 'int'),
	('Hunting Log - Slain - Jyuratodus', gSaveMon, [0x274], 'int'),
	('Hunting Log - Slain - Tobi-Kadachi', gSaveMon, [0x278], 'int'),
	('Hunting Log - Slain - Paolumu', gSaveMon, [0x27C], 'int'),
	('Hunting Log - Slain - Legiana', gSaveMon, [0x280], 'int'),
	('Hunting Log - Slain - Great Girros', gSaveMon, [0x284], 'int'),
	('Hunting Log - Slain - Odogaron', gSaveMon, [0x288], 'int'),
	('Hunting Log - Slain - Radobaan', gSaveMon, [0x28C], 'int'),
	('Hunting Log - Slain - Vaal Hazak', gSaveMon, [0x290], 'int'),
	('Hunting Log - Slain - Dodogama', gSaveMon, [0x294], 'int'),
	('Hunting Log - Slain - Kulve Taroth', gSaveMon, [0x298], 'int'),
	('Hunting Log - Slain - Bazelgeuse', gSaveMon, [0x29C], 'int'),
	('Hunting Log - Slain - Apceros', gSaveMon, [0x2A0], 'int'),
	('Hunting Log - Slain - Kelbi (male)', gSaveMon, [0x2A4], 'int'),
	('Hunting Log - Slain - Kelbi (female)', gSaveMon, [0x2A8], 'int'),
	('Hunting Log - Slain - Hornetaur', gSaveMon, [0x2AC], 'int'),
	('Hunting Log - Slain - Vespoid', gSaveMon, [0x2B0], 'int'),
	('Hunting Log - Slain - Mernos', gSaveMon, [0x2B4], 'int'),
	('Hunting Log - Slain - Kestodon (female)', gSaveMon, [0x2B8], 'int'),
	('Hunting Log - Slain - Raphinos', gSaveMon, [0x2BC], 'int'),
	('Hunting Log - Slain - Shamos', gSaveMon, [0x2C0], 'int'),
	('Hunting Log - Slain - Barnos', gSaveMon, [0x2C4], 'int'),
	('Hunting Log - Slain - Girros', gSaveMon, [0x2C8], 'int'),
	('Hunting Log - Slain - Ancient Leshen', gSaveMon, [0x2CC], 'int'),
	('Hunting Log - Slain - Gastodon', gSaveMon, [0x2D0], 'int'),
	('Hunting Log - Slain - Noios', gSaveMon, [0x2D4], 'int'),
	('Hunting Log - Slain - Gajalaka', gSaveMon, [0x2E0], 'int'),
	('Hunting Log - Slain - Tigrex', gSaveMon, [0x2F4], 'int'),
	('Hunting Log - Slain - Nargacuga', gSaveMon, [0x2F8], 'int'),
	('Hunting Log - Slain - Barioth', gSaveMon, [0x2FC], 'int'),
	('Hunting Log - Slain - Savage Deviljho', gSaveMon, [0x300], 'int'),
	('Hunting Log - Slain - Brachydios', gSaveMon, [0x304], 'int'),
	('Hunting Log - Slain - Glavenus', gSaveMon, [0x308], 'int'),
	('Hunting Log - Slain - Acidic Glavenus', gSaveMon, [0x30C], 'int'),
	('Hunting Log - Slain - Fulgur Anjanath', gSaveMon, [0x310], 'int'),
	('Hunting Log - Slain - Coral Pukei-Pukei', gSaveMon, [0x314], 'int'),
	('Hunting Log - Slain - Ruiner Nergigante', gSaveMon, [0x318], 'int'),
	('Hunting Log - Slain - Viper Tobi-Kadachi', gSaveMon, [0x31C], 'int'),
	('Hunting Log - Slain - Nightshade Paolumu', gSaveMon, [0x320], 'int'),
	('Hunting Log - Slain - Shrieking Legiana', gSaveMon, [0x324], 'int'),
	('Hunting Log - Slain - Ebony Odogaron', gSaveMon, [0x328], 'int'),
	('Hunting Log - Slain - Blackveil Vaal Hazak', gSaveMon, [0x32C], 'int'),
	('Hunting Log - Slain - Seething Bazelgeuse', gSaveMon, [0x330], 'int'),
	('Hunting Log - Slain - Beotodus', gSaveMon, [0x334], 'int'),
	('Hunting Log - Slain - Banbaro', gSaveMon, [0x338], 'int'),
	('Hunting Log - Slain - Velkhana', gSaveMon, [0x33C], 'int'),
	('Hunting Log - Slain - Namielle', gSaveMon, [0x340], 'int'),
	('Hunting Log - Slain - Shara Ishvalda', gSaveMon, [0x344], 'int'),
	('Hunting Log - Slain - Popo', gSaveMon, [0x348], 'int'),
	('Hunting Log - Slain - Anteka', gSaveMon, [0x34C], 'int'),
	('Hunting Log - Slain - Wulg', gSaveMon, [0x350], 'int'),
	('Hunting Log - Slain - Cortos', gSaveMon, [0x354], 'int'),
	('Hunting Log - Slain - Boaboa', gSaveMon, [0x358], 'int'),
	('Hunting Log - Slain - Alatreon', gSaveMon, [0x35C], 'int'),
	('Hunting Log - Slain - Gold Rathian', gSaveMon, [0x360], 'int'),
	('Hunting Log - Slain - Silver Rathalos', gSaveMon, [0x364], 'int'),
	('Hunting Log - Slain - Yian Garuga', gSaveMon, [0x368], 'int'),
	('Hunting Log - Slain - Rajang', gSaveMon, [0x36C], 'int'),
	('Hunting Log - Slain - Furious Rajang', gSaveMon, [0x370], 'int'),
	('Hunting Log - Slain - Brute Tigrex', gSaveMon, [0x374], 'int'),
	('Hunting Log - Slain - Zinogre', gSaveMon, [0x378], 'int'),
	('Hunting Log - Slain - Stygian Zinogre', gSaveMon, [0x37C], 'int'),
	('Hunting Log - Slain - Raging Brachydios', gSaveMon, [0x380], 'int'),
	('Hunting Log - Slain - Safi\'jiiva', gSaveMon, [0x384], 'int'),
	('Hunting Log - Slain - Scarred Yian Garuga', gSaveMon, [0x38C], 'int'),
	('Hunting Log - Slain - Frostfang Barioth', gSaveMon, [0x390], 'int'),
	('Hunting Log - Slain - Fatalis', gSaveMon, [0x394], 'int'),
	('Hunting Log - Large Crown Size - Anjanath', gSaveMon, [0xC00], 'int'),
	('Hunting Log - Large Crown Size - Rathalos', gSaveMon, [0xC04], 'int'),
	('Hunting Log - Large Crown Size - Aptonoth', gSaveMon, [0xC08], 'int'),
	('Hunting Log - Large Crown Size - Jagras', gSaveMon, [0xC0C], 'int'),
	('Hunting Log - Large Crown Size - Zorah Magdaros', gSaveMon, [0xC10], 'int'),
	('Hunting Log - Large Crown Size - Mosswine', gSaveMon, [0xC14], 'int'),
	('Hunting Log - Large Crown Size - Gajau', gSaveMon, [0xC18], 'int'),
	('Hunting Log - Large Crown Size - Great Jagras', gSaveMon, [0xC1C], 'int'),
	('Hunting Log - Large Crown Size - Kestodon (male)', gSaveMon, [0xC20], 'int'),
	('Hunting Log - Large Crown Size - Rathian', gSaveMon, [0xC24], 'int'),
	('Hunting Log - Large Crown Size - Pink Rathian', gSaveMon, [0xC28], 'int'),
	('Hunting Log - Large Crown Size - Azure Rathalos', gSaveMon, [0xC2C], 'int'),
	('Hunting Log - Large Crown Size - Diablos', gSaveMon, [0xC30], 'int'),
	('Hunting Log - Large Crown Size - Black Diablos', gSaveMon, [0xC34], 'int'),
	('Hunting Log - Large Crown Size - Kirin', gSaveMon, [0xC38], 'int'),
	('Hunting Log - Large Crown Size - Behemoth', gSaveMon, [0xC3C], 'int'),
	('Hunting Log - Large Crown Size - Kushala Daora', gSaveMon, [0xC40], 'int'),
	('Hunting Log - Large Crown Size - Lunastra', gSaveMon, [0xC44], 'int'),
	('Hunting Log - Large Crown Size - Teostra', gSaveMon, [0xC48], 'int'),
	('Hunting Log - Large Crown Size - Lavasioth', gSaveMon, [0xC4C], 'int'),
	('Hunting Log - Large Crown Size - Deviljho', gSaveMon, [0xC50], 'int'),
	('Hunting Log - Large Crown Size - Barroth', gSaveMon, [0xC54], 'int'),
	('Hunting Log - Large Crown Size - Uragaan', gSaveMon, [0xC58], 'int'),
	('Hunting Log - Large Crown Size - Leshen', gSaveMon, [0xC5C], 'int'),
	('Hunting Log - Large Crown Size - Pukei-Pukei', gSaveMon, [0xC60], 'int'),
	('Hunting Log - Large Crown Size - Nergigante', gSaveMon, [0xC64], 'int'),
	('Hunting Log - Large Crown Size - Xeno\'jiiva', gSaveMon, [0xC68], 'int'),
	('Hunting Log - Large Crown Size - Kulu-Ya-Ku', gSaveMon, [0xC6C], 'int'),
	('Hunting Log - Large Crown Size - Tzitzi-Ya-Ku', gSaveMon, [0xC70], 'int'),
	('Hunting Log - Large Crown Size - Jyuratodus', gSaveMon, [0xC74], 'int'),
	('Hunting Log - Large Crown Size - Tobi-Kadachi', gSaveMon, [0xC78], 'int'),
	('Hunting Log - Large Crown Size - Paolumu', gSaveMon, [0xC7C], 'int'),
	('Hunting Log - Large Crown Size - Legiana', gSaveMon, [0xC80], 'int'),
	('Hunting Log - Large Crown Size - Great Girros', gSaveMon, [0xC84], 'int'),
	('Hunting Log - Large Crown Size - Odogaron', gSaveMon, [0xC88], 'int'),
	('Hunting Log - Large Crown Size - Radobaan', gSaveMon, [0xC8C], 'int'),
	('Hunting Log - Large Crown Size - Vaal Hazak', gSaveMon, [0xC90], 'int'),
	('Hunting Log - Large Crown Size - Dodogama', gSaveMon, [0xC94], 'int'),
	('Hunting Log - Large Crown Size - Kulve Taroth', gSaveMon, [0xC98], 'int'),
	('Hunting Log - Large Crown Size - Bazelgeuse', gSaveMon, [0xC9C], 'int'),
	('Hunting Log - Large Crown Size - Apceros', gSaveMon, [0xCA0], 'int'),
	('Hunting Log - Large Crown Size - Kelbi (male)', gSaveMon, [0xCA4], 'int'),
	('Hunting Log - Large Crown Size - Kelbi (female)', gSaveMon, [0xCA8], 'int'),
	('Hunting Log - Large Crown Size - Hornetaur', gSaveMon, [0xCAC], 'int'),
	('Hunting Log - Large Crown Size - Vespoid', gSaveMon, [0xCB0], 'int'),
	('Hunting Log - Large Crown Size - Mernos', gSaveMon, [0xCB4], 'int'),
	('Hunting Log - Large Crown Size - Kestodon (female)', gSaveMon, [0xCB8], 'int'),
	('Hunting Log - Large Crown Size - Raphinos', gSaveMon, [0xCBC], 'int'),
	('Hunting Log - Large Crown Size - Shamos', gSaveMon, [0xCC0], 'int'),
	('Hunting Log - Large Crown Size - Barnos', gSaveMon, [0xCC4], 'int'),
	('Hunting Log - Large Crown Size - Girros', gSaveMon, [0xCC8], 'int'),
	('Hunting Log - Large Crown Size - Ancient Leshen', gSaveMon, [0xCCC], 'int'),
	('Hunting Log - Large Crown Size - Gastodon', gSaveMon, [0xCD0], 'int'),
	('Hunting Log - Large Crown Size - Noios', gSaveMon, [0xCD4], 'int'),
	('Hunting Log - Large Crown Size - Gajalaka', gSaveMon, [0xCE0], 'int'),
	('Hunting Log - Large Crown Size - Tigrex', gSaveMon, [0xCF4], 'int'),
	('Hunting Log - Large Crown Size - Nargacuga', gSaveMon, [0xCF8], 'int'),
	('Hunting Log - Large Crown Size - Barioth', gSaveMon, [0xCFC], 'int'),
	('Hunting Log - Large Crown Size - Savage Deviljho', gSaveMon, [0xD00], 'int'),
	('Hunting Log - Large Crown Size - Brachydios', gSaveMon, [0xD04], 'int'),
	('Hunting Log - Large Crown Size - Glavenus', gSaveMon, [0xD08], 'int'),
	('Hunting Log - Large Crown Size - Acidic Glavenus', gSaveMon, [0xD0C], 'int'),
	('Hunting Log - Large Crown Size - Fulgur Anjanath', gSaveMon, [0xD10], 'int'),
	('Hunting Log - Large Crown Size - Coral Pukei-Pukei', gSaveMon, [0xD14], 'int'),
	('Hunting Log - Large Crown Size - Ruiner Nergigante', gSaveMon, [0xD18], 'int'),
	('Hunting Log - Large Crown Size - Viper Tobi-Kadachi', gSaveMon, [0xD1C], 'int'),
	('Hunting Log - Large Crown Size - Nightshade Paolumu', gSaveMon, [0xD20], 'int'),
	('Hunting Log - Large Crown Size - Shrieking Legiana', gSaveMon, [0xD24], 'int'),
	('Hunting Log - Large Crown Size - Ebony Odogaron', gSaveMon, [0xD28], 'int'),
	('Hunting Log - Large Crown Size - Blackveil Vaal Hazak', gSaveMon, [0xD2C], 'int'),
	('Hunting Log - Large Crown Size - Seething Bazelgeuse', gSaveMon, [0xD30], 'int'),
	('Hunting Log - Large Crown Size - Beotodus', gSaveMon, [0xD34], 'int'),
	('Hunting Log - Large Crown Size - Banbaro', gSaveMon, [0xD38], 'int'),
	('Hunting Log - Large Crown Size - Velkhana', gSaveMon, [0xD3C], 'int'),
	('Hunting Log - Large Crown Size - Namielle', gSaveMon, [0xD40], 'int'),
	('Hunting Log - Large Crown Size - Shara Ishvalda', gSaveMon, [0xD44], 'int'),
	('Hunting Log - Large Crown Size - Popo', gSaveMon, [0xD48], 'int'),
	('Hunting Log - Large Crown Size - Anteka', gSaveMon, [0xD4C], 'int'),
	('Hunting Log - Large Crown Size - Wulg', gSaveMon, [0xD50], 'int'),
	('Hunting Log - Large Crown Size - Cortos', gSaveMon, [0xD54], 'int'),
	('Hunting Log - Large Crown Size - Boaboa', gSaveMon, [0xD58], 'int'),
	('Hunting Log - Large Crown Size - Alatreon', gSaveMon, [0xD5C], 'int'),
	('Hunting Log - Large Crown Size - Gold Rathian', gSaveMon, [0xD60], 'int'),
	('Hunting Log - Large Crown Size - Silver Rathalos', gSaveMon, [0xD64], 'int'),
	('Hunting Log - Large Crown Size - Yian Garuga', gSaveMon, [0xD68], 'int'),
	('Hunting Log - Large Crown Size - Rajang', gSaveMon, [0xD6C], 'int'),
	('Hunting Log - Large Crown Size - Furious Rajang', gSaveMon, [0xD70], 'int'),
	('Hunting Log - Large Crown Size - Brute Tigrex', gSaveMon, [0xD74], 'int'),
	('Hunting Log - Large Crown Size - Zinogre', gSaveMon, [0xD78], 'int'),
	('Hunting Log - Large Crown Size - Stygian Zinogre', gSaveMon, [0xD7C], 'int'),
	('Hunting Log - Large Crown Size - Raging Brachydios', gSaveMon, [0xD80], 'int'),
	('Hunting Log - Large Crown Size - Safi\'jiiva', gSaveMon, [0xD84], 'int'),
	('Hunting Log - Large Crown Size - Scarred Yian Garuga', gSaveMon, [0xD88], 'int'),
	('Hunting Log - Large Crown Size - Frostfang Barioth', gSaveMon, [0xD8C], 'int'),
	('Hunting Log - Large Crown Size - Fatalis', gSaveMon, [0xD90], 'int'),
	('Hunting Log - Small Crown Size - Anjanath', gSaveMon, [0xE00], 'int'),
	('Hunting Log - Small Crown Size - Rathalos', gSaveMon, [0xE04], 'int'),
	('Hunting Log - Small Crown Size - Aptonoth', gSaveMon, [0xE08], 'int'),
	('Hunting Log - Small Crown Size - Jagras', gSaveMon, [0xE0C], 'int'),
	('Hunting Log - Small Crown Size - Zorah Magdaros', gSaveMon, [0xE10], 'int'),
	('Hunting Log - Small Crown Size - Mosswine', gSaveMon, [0xE14], 'int'),
	('Hunting Log - Small Crown Size - Gajau', gSaveMon, [0xE18], 'int'),
	('Hunting Log - Small Crown Size - Great Jagras', gSaveMon, [0xE1C], 'int'),
	('Hunting Log - Small Crown Size - Kestodon (male)', gSaveMon, [0xE20], 'int'),
	('Hunting Log - Small Crown Size - Rathian', gSaveMon, [0xE24], 'int'),
	('Hunting Log - Small Crown Size - Pink Rathian', gSaveMon, [0xE28], 'int'),
	('Hunting Log - Small Crown Size - Azure Rathalos', gSaveMon, [0xE2C], 'int'),
	('Hunting Log - Small Crown Size - Diablos', gSaveMon, [0xE30], 'int'),
	('Hunting Log - Small Crown Size - Black Diablos', gSaveMon, [0xE34], 'int'),
	('Hunting Log - Small Crown Size - Kirin', gSaveMon, [0xE38], 'int'),
	('Hunting Log - Small Crown Size - Behemoth', gSaveMon, [0xE3C], 'int'),
	('Hunting Log - Small Crown Size - Kushala Daora', gSaveMon, [0xE40], 'int'),
	('Hunting Log - Small Crown Size - Lunastra', gSaveMon, [0xE44], 'int'),
	('Hunting Log - Small Crown Size - Teostra', gSaveMon, [0xE48], 'int'),
	('Hunting Log - Small Crown Size - Lavasioth', gSaveMon, [0xE4C], 'int'),
	('Hunting Log - Small Crown Size - Deviljho', gSaveMon, [0xE50], 'int'),
	('Hunting Log - Small Crown Size - Barroth', gSaveMon, [0xE54], 'int'),
	('Hunting Log - Small Crown Size - Uragaan', gSaveMon, [0xE58], 'int'),
	('Hunting Log - Small Crown Size - Leshen', gSaveMon, [0xE5C], 'int'),
	('Hunting Log - Small Crown Size - Pukei-Pukei', gSaveMon, [0xE60], 'int'),
	('Hunting Log - Small Crown Size - Nergigante', gSaveMon, [0xE64], 'int'),
	('Hunting Log - Small Crown Size - Xeno\'jiiva', gSaveMon, [0xE68], 'int'),
	('Hunting Log - Small Crown Size - Kulu-Ya-Ku', gSaveMon, [0xE6C], 'int'),
	('Hunting Log - Small Crown Size - Tzitzi-Ya-Ku', gSaveMon, [0xE70], 'int'),
	('Hunting Log - Small Crown Size - Jyuratodus', gSaveMon, [0xE74], 'int'),
	('Hunting Log - Small Crown Size - Tobi-Kadachi', gSaveMon, [0xE78], 'int'),
	('Hunting Log - Small Crown Size - Paolumu', gSaveMon, [0xE7C], 'int'),
	('Hunting Log - Small Crown Size - Legiana', gSaveMon, [0xE80], 'int'),
	('Hunting Log - Small Crown Size - Great Girros', gSaveMon, [0xE84], 'int'),
	('Hunting Log - Small Crown Size - Odogaron', gSaveMon, [0xE88], 'int'),
	('Hunting Log - Small Crown Size - Radobaan', gSaveMon, [0xE8C], 'int'),
	('Hunting Log - Small Crown Size - Vaal Hazak', gSaveMon, [0xE90], 'int'),
	('Hunting Log - Small Crown Size - Dodogama', gSaveMon, [0xE94], 'int'),
	('Hunting Log - Small Crown Size - Kulve Taroth', gSaveMon, [0xE98], 'int'),
	('Hunting Log - Small Crown Size - Bazelgeuse', gSaveMon, [0xE9C], 'int'),
	('Hunting Log - Small Crown Size - Apceros', gSaveMon, [0xEA0], 'int'),
	('Hunting Log - Small Crown Size - Kelbi (male)', gSaveMon, [0xEA4], 'int'),
	('Hunting Log - Small Crown Size - Kelbi (female)', gSaveMon, [0xEA8], 'int'),
	('Hunting Log - Small Crown Size - Hornetaur', gSaveMon, [0xEAC], 'int'),
	('Hunting Log - Small Crown Size - Vespoid', gSaveMon, [0xEB0], 'int'),
	('Hunting Log - Small Crown Size - Mernos', gSaveMon, [0xEB4], 'int'),
	('Hunting Log - Small Crown Size - Kestodon (female)', gSaveMon, [0xEB8], 'int'),
	('Hunting Log - Small Crown Size - Raphinos', gSaveMon, [0xEBC], 'int'),
	('Hunting Log - Small Crown Size - Shamos', gSaveMon, [0xEC0], 'int'),
	('Hunting Log - Small Crown Size - Barnos', gSaveMon, [0xEC4], 'int'),
	('Hunting Log - Small Crown Size - Girros', gSaveMon, [0xEC8], 'int'),
	('Hunting Log - Small Crown Size - Ancient Leshen', gSaveMon, [0xECC], 'int'),
	('Hunting Log - Small Crown Size - Gastodon', gSaveMon, [0xED0], 'int'),
	('Hunting Log - Small Crown Size - Noios', gSaveMon, [0xED4], 'int'),
	('Hunting Log - Small Crown Size - Gajalaka', gSaveMon, [0xEE0], 'int'),
	('Hunting Log - Small Crown Size - Tigrex', gSaveMon, [0xEF4], 'int'),
	('Hunting Log - Small Crown Size - Nargacuga', gSaveMon, [0xEF8], 'int'),
	('Hunting Log - Small Crown Size - Barioth', gSaveMon, [0xEFC], 'int'),
	('Hunting Log - Small Crown Size - Savage Deviljho', gSaveMon, [0xF00], 'int'),
	('Hunting Log - Small Crown Size - Brachydios', gSaveMon, [0xF04], 'int'),
	('Hunting Log - Small Crown Size - Glavenus', gSaveMon, [0xF08], 'int'),
	('Hunting Log - Small Crown Size - Acidic Glavenus', gSaveMon, [0xF0C], 'int'),
	('Hunting Log - Small Crown Size - Fulgur Anjanath', gSaveMon, [0xF10], 'int'),
	('Hunting Log - Small Crown Size - Coral Pukei-Pukei', gSaveMon, [0xF14], 'int'),
	('Hunting Log - Small Crown Size - Ruiner Nergigante', gSaveMon, [0xF18], 'int'),
	('Hunting Log - Small Crown Size - Viper Tobi-Kadachi', gSaveMon, [0xF1C], 'int'),
	('Hunting Log - Small Crown Size - Nightshade Paolumu', gSaveMon, [0xF20], 'int'),
	('Hunting Log - Small Crown Size - Shrieking Legiana', gSaveMon, [0xF24], 'int'),
	('Hunting Log - Small Crown Size - Ebony Odogaron', gSaveMon, [0xF28], 'int'),
	('Hunting Log - Small Crown Size - Blackveil Vaal Hazak', gSaveMon, [0xF2C], 'int'),
	('Hunting Log - Small Crown Size - Seething Bazelgeuse', gSaveMon, [0xF30], 'int'),
	('Hunting Log - Small Crown Size - Beotodus', gSaveMon, [0xF34], 'int'),
	('Hunting Log - Small Crown Size - Banbaro', gSaveMon, [0xF38], 'int'),
	('Hunting Log - Small Crown Size - Velkhana', gSaveMon, [0xF3C], 'int'),
	('Hunting Log - Small Crown Size - Namielle', gSaveMon, [0xF40], 'int'),
	('Hunting Log - Small Crown Size - Shara Ishvalda', gSaveMon, [0xF44], 'int'),
	('Hunting Log - Small Crown Size - Popo', gSaveMon, [0xF48], 'int'),
	('Hunting Log - Small Crown Size - Anteka', gSaveMon, [0xF4C], 'int'),
	('Hunting Log - Small Crown Size - Wulg', gSaveMon, [0xF50], 'int'),
	('Hunting Log - Small Crown Size - Cortos', gSaveMon, [0xF54], 'int'),
	('Hunting Log - Small Crown Size - Boaboa', gSaveMon, [0xF58], 'int'),
	('Hunting Log - Small Crown Size - Alatreon', gSaveMon, [0xF5C], 'int'),
	('Hunting Log - Small Crown Size - Gold Rathian', gSaveMon, [0xF60], 'int'),
	('Hunting Log - Small Crown Size - Silver Rathalos', gSaveMon, [0xF64], 'int'),
	('Hunting Log - Small Crown Size - Yian Garuga', gSaveMon, [0xF68], 'int'),
	('Hunting Log - Small Crown Size - Rajang', gSaveMon, [0xF6C], 'int'),
	('Hunting Log - Small Crown Size - Furious Rajang', gSaveMon, [0xF70], 'int'),
	('Hunting Log - Small Crown Size - Brute Tigrex', gSaveMon, [0xF74], 'int'),
	('Hunting Log - Small Crown Size - Zinogre', gSaveMon, [0xF78], 'int'),
	('Hunting Log - Small Crown Size - Stygian Zinogre', gSaveMon, [0xF7C], 'int'),
	('Hunting Log - Small Crown Size - Raging Brachydios', gSaveMon, [0xF80], 'int'),
	('Hunting Log - Small Crown Size - Safi\'jiiva', gSaveMon, [0xF84], 'int'),
	('Hunting Log - Small Crown Size - Scarred Yian Garuga', gSaveMon, [0xF88], 'int'),
	('Hunting Log - Small Crown Size - Frostfang Barioth', gSaveMon, [0xF8C], 'int'),
	('Hunting Log - Small Crown Size - Fatalis', gSaveMon, [0xF90], 'int'),
	('Hunting Log - Research Experience - Anjanath', gSaveMon, [0x1000], 'float'),
	('Hunting Log - Research Experience - Rathalos', gSaveMon, [0x1004], 'float'),
	('Hunting Log - Research Experience - Aptonoth', gSaveMon, [0x1008], 'float'),
	('Hunting Log - Research Experience - Jagras', gSaveMon, [0x100C], 'float'),
	('Hunting Log - Research Experience - Zorah Magdaros', gSaveMon, [0x1010], 'float'),
	('Hunting Log - Research Experience - Mosswine', gSaveMon, [0x1014], 'float'),
	('Hunting Log - Research Experience - Gajau', gSaveMon, [0x1018], 'float'),
	('Hunting Log - Research Experience - Great Jagras', gSaveMon, [0x101C], 'float'),
	('Hunting Log - Research Experience - Kestodon (male)', gSaveMon, [0x1020], 'float'),
	('Hunting Log - Research Experience - Rathian', gSaveMon, [0x1024], 'float'),
	('Hunting Log - Research Experience - Pink Rathian', gSaveMon, [0x1028], 'float'),
	('Hunting Log - Research Experience - Azure Rathalos', gSaveMon, [0x102C], 'float'),
	('Hunting Log - Research Experience - Diablos', gSaveMon, [0x1030], 'float'),
	('Hunting Log - Research Experience - Black Diablos', gSaveMon, [0x1034], 'float'),
	('Hunting Log - Research Experience - Kirin', gSaveMon, [0x1038], 'float'),
	('Hunting Log - Research Experience - Behemoth', gSaveMon, [0x103C], 'float'),
	('Hunting Log - Research Experience - Kushala Daora', gSaveMon, [0x1040], 'float'),
	('Hunting Log - Research Experience - Lunastra', gSaveMon, [0x1044], 'float'),
	('Hunting Log - Research Experience - Teostra', gSaveMon, [0x1048], 'float'),
	('Hunting Log - Research Experience - Lavasioth', gSaveMon, [0x104C], 'float'),
	('Hunting Log - Research Experience - Deviljho', gSaveMon, [0x1050], 'float'),
	('Hunting Log - Research Experience - Barroth', gSaveMon, [0x1054], 'float'),
	('Hunting Log - Research Experience - Uragaan', gSaveMon, [0x1058], 'float'),
	('Hunting Log - Research Experience - Leshen', gSaveMon, [0x105C], 'float'),
	('Hunting Log - Research Experience - Pukei-Pukei', gSaveMon, [0x1060], 'float'),
	('Hunting Log - Research Experience - Nergigante', gSaveMon, [0x1064], 'float'),
	('Hunting Log - Research Experience - Xeno\'jiiva', gSaveMon, [0x1068], 'float'),
	('Hunting Log - Research Experience - Kulu-Ya-Ku', gSaveMon, [0x106C], 'float'),
	('Hunting Log - Research Experience - Tzitzi-Ya-Ku', gSaveMon, [0x1070], 'float'),
	('Hunting Log - Research Experience - Jyuratodus', gSaveMon, [0x1074], 'float'),
	('Hunting Log - Research Experience - Tobi-Kadachi', gSaveMon, [0x1078], 'float'),
	('Hunting Log - Research Experience - Paolumu', gSaveMon, [0x107C], 'float'),
	('Hunting Log - Research Experience - Legiana', gSaveMon, [0x1080], 'float'),
	('Hunting Log - Research Experience - Great Girros', gSaveMon, [0x1084], 'float'),
	('Hunting Log - Research Experience - Odogaron', gSaveMon, [0x1088], 'float'),
	('Hunting Log - Research Experience - Radobaan', gSaveMon, [0x108C], 'float'),
	('Hunting Log - Research Experience - Vaal Hazak', gSaveMon, [0x1090], 'float'),
	('Hunting Log - Research Experience - Dodogama', gSaveMon, [0x1094], 'float'),
	('Hunting Log - Research Experience - Kulve Taroth', gSaveMon, [0x1098], 'float'),
	('Hunting Log - Research Experience - Bazelgeuse', gSaveMon, [0x109C], 'float'),
	('Hunting Log - Research Experience - Apceros', gSaveMon, [0x10A0], 'float'),
	('Hunting Log - Research Experience - Kelbi (male)', gSaveMon, [0x10A4], 'float'),
	('Hunting Log - Research Experience - Kelbi (female)', gSaveMon, [0x10A8], 'float'),
	('Hunting Log - Research Experience - Hornetaur', gSaveMon, [0x10AC], 'float'),
	('Hunting Log - Research Experience - Vespoid', gSaveMon, [0x10B0], 'float'),
	('Hunting Log - Research Experience - Mernos', gSaveMon, [0x10B4], 'float'),
	('Hunting Log - Research Experience - Kestodon (female)', gSaveMon, [0x10B8], 'float'),
	('Hunting Log - Research Experience - Raphinos', gSaveMon, [0x10BC], 'float'),
	('Hunting Log - Research Experience - Shamos', gSaveMon, [0x10C0], 'float'),
	('Hunting Log - Research Experience - Barnos', gSaveMon, [0x10C4], 'float'),
	('Hunting Log - Research Experience - Girros', gSaveMon, [0x10C8], 'float'),
	('Hunting Log - Research Experience - Ancient Leshen', gSaveMon, [0x10CC], 'float'),
	('Hunting Log - Research Experience - Gastodon', gSaveMon, [0x10D0], 'float'),
	('Hunting Log - Research Experience - Noios', gSaveMon, [0x10D4], 'float'),
	('Hunting Log - Research Experience - Gajalaka', gSaveMon, [0x10E0], 'float'),
	('Hunting Log - Research Experience - Tigrex', gSaveMon, [0x10F4], 'float'),
	('Hunting Log - Research Experience - Nargacuga', gSaveMon, [0x10F8], 'float'),
	('Hunting Log - Research Experience - Barioth', gSaveMon, [0x10FC], 'float'),
	('Hunting Log - Research Experience - Savage Deviljho', gSaveMon, [0x1100], 'float'),
	('Hunting Log - Research Experience - Brachydios', gSaveMon, [0x1104], 'float'),
	('Hunting Log - Research Experience - Glavenus', gSaveMon, [0x1108], 'float'),
	('Hunting Log - Research Experience - Acidic Glavenus', gSaveMon, [0x110C], 'float'),
	('Hunting Log - Research Experience - Fulgur Anjanath', gSaveMon, [0x1110], 'float'),
	('Hunting Log - Research Experience - Coral Pukei-Pukei', gSaveMon, [0x1114], 'float'),
	('Hunting Log - Research Experience - Ruiner Nergigante', gSaveMon, [0x1118], 'float'),
	('Hunting Log - Research Experience - Viper Tobi-Kadachi', gSaveMon, [0x111C], 'float'),
	('Hunting Log - Research Experience - Nightshade Paolumu', gSaveMon, [0x1120], 'float'),
	('Hunting Log - Research Experience - Shrieking Legiana', gSaveMon, [0x1124], 'float'),
	('Hunting Log - Research Experience - Ebony Odogaron', gSaveMon, [0x1128], 'float'),
	('Hunting Log - Research Experience - Blackveil Vaal Hazak', gSaveMon, [0x112C], 'float'),
	('Hunting Log - Research Experience - Seething Bazelgeuse', gSaveMon, [0x1130], 'float'),
	('Hunting Log - Research Experience - Beotodus', gSaveMon, [0x1134], 'float'),
	('Hunting Log - Research Experience - Banbaro', gSaveMon, [0x1138], 'float'),
	('Hunting Log - Research Experience - Velkhana', gSaveMon, [0x113C], 'float'),
	('Hunting Log - Research Experience - Namielle', gSaveMon, [0x1140], 'float'),
	('Hunting Log - Research Experience - Shara Ishvalda', gSaveMon, [0x1144], 'float'),
	('Hunting Log - Research Experience - Popo', gSaveMon, [0x1148], 'float'),
	('Hunting Log - Research Experience - Anteka', gSaveMon, [0x114C], 'float'),
	('Hunting Log - Research Experience - Wulg', gSaveMon, [0x1150], 'float'),
	('Hunting Log - Research Experience - Cortos', gSaveMon, [0x1154], 'float'),
	('Hunting Log - Research Experience - Boaboa', gSaveMon, [0x1158], 'float'),
	('Hunting Log - Research Experience - Alatreon', gSaveMon, [0x115C], 'float'),
	('Hunting Log - Research Experience - Gold Rathian', gSaveMon, [0x1160], 'float'),
	('Hunting Log - Research Experience - Silver Rathalos', gSaveMon, [0x1164], 'float'),
	('Hunting Log - Research Experience - Yian Garuga', gSaveMon, [0x1168], 'float'),
	('Hunting Log - Research Experience - Rajang', gSaveMon, [0x116C], 'float'),
	('Hunting Log - Research Experience - Furious Rajang', gSaveMon, [0x1170], 'float'),
	('Hunting Log - Research Experience - Brute Tigrex', gSaveMon, [0x1174], 'float'),
	('Hunting Log - Research Experience - Zinogre', gSaveMon, [0x1178], 'float'),
	('Hunting Log - Research Experience - Stygian Zinogre', gSaveMon, [0x117C], 'float'),
	('Hunting Log - Research Experience - Raging Brachydios', gSaveMon, [0x1180], 'float'),
	('Hunting Log - Research Experience - Safi\'jiiva', gSaveMon, [0x1184], 'float'),
	('Hunting Log - Research Experience - Scarred Yian Garuga', gSaveMon, [0x1188], 'float'),
	('Hunting Log - Research Experience - Frostfang Barioth', gSaveMon, [0x118C], 'float'),
	('Hunting Log - Research Experience - Fatalis', gSaveMon, [0x1190], 'float'),
	('Hunting Log - Research Level - Anjanath', gSaveMon, [0x1200], 'int'),
	('Hunting Log - Research Level - Rathalos', gSaveMon, [0x1204], 'int'),
	('Hunting Log - Research Level - Aptonoth', gSaveMon, [0x1208], 'int'),
	('Hunting Log - Research Level - Jagras', gSaveMon, [0x120C], 'int'),
	('Hunting Log - Research Level - Zorah Magdaros', gSaveMon, [0x1210], 'int'),
	('Hunting Log - Research Level - Mosswine', gSaveMon, [0x1214], 'int'),
	('Hunting Log - Research Level - Gajau', gSaveMon, [0x1218], 'int'),
	('Hunting Log - Research Level - Great Jagras', gSaveMon, [0x121C], 'int'),
	('Hunting Log - Research Level - Kestodon (male)', gSaveMon, [0x1220], 'int'),
	('Hunting Log - Research Level - Rathian', gSaveMon, [0x1224], 'int'),
	('Hunting Log - Research Level - Pink Rathian', gSaveMon, [0x1228], 'int'),
	('Hunting Log - Research Level - Azure Rathalos', gSaveMon, [0x122C], 'int'),
	('Hunting Log - Research Level - Diablos', gSaveMon, [0x1230], 'int'),
	('Hunting Log - Research Level - Black Diablos', gSaveMon, [0x1234], 'int'),
	('Hunting Log - Research Level - Kirin', gSaveMon, [0x1238], 'int'),
	('Hunting Log - Research Level - Behemoth', gSaveMon, [0x123C], 'int'),
	('Hunting Log - Research Level - Kushala Daora', gSaveMon, [0x1240], 'int'),
	('Hunting Log - Research Level - Lunastra', gSaveMon, [0x1244], 'int'),
	('Hunting Log - Research Level - Teostra', gSaveMon, [0x1248], 'int'),
	('Hunting Log - Research Level - Lavasioth', gSaveMon, [0x124C], 'int'),
	('Hunting Log - Research Level - Deviljho', gSaveMon, [0x1250], 'int'),
	('Hunting Log - Research Level - Barroth', gSaveMon, [0x1254], 'int'),
	('Hunting Log - Research Level - Uragaan', gSaveMon, [0x1258], 'int'),
	('Hunting Log - Research Level - Leshen', gSaveMon, [0x125C], 'int'),
	('Hunting Log - Research Level - Pukei-Pukei', gSaveMon, [0x1260], 'int'),
	('Hunting Log - Research Level - Nergigante', gSaveMon, [0x1264], 'int'),
	('Hunting Log - Research Level - Xeno\'jiiva', gSaveMon, [0x1268], 'int'),
	('Hunting Log - Research Level - Kulu-Ya-Ku', gSaveMon, [0x126C], 'int'),
	('Hunting Log - Research Level - Tzitzi-Ya-Ku', gSaveMon, [0x1270], 'int'),
	('Hunting Log - Research Level - Jyuratodus', gSaveMon, [0x1274], 'int'),
	('Hunting Log - Research Level - Tobi-Kadachi', gSaveMon, [0x1278], 'int'),
	('Hunting Log - Research Level - Paolumu', gSaveMon, [0x127C], 'int'),
	('Hunting Log - Research Level - Legiana', gSaveMon, [0x1280], 'int'),
	('Hunting Log - Research Level - Great Girros', gSaveMon, [0x1284], 'int'),
	('Hunting Log - Research Level - Odogaron', gSaveMon, [0x1288], 'int'),
	('Hunting Log - Research Level - Radobaan', gSaveMon, [0x128C], 'int'),
	('Hunting Log - Research Level - Vaal Hazak', gSaveMon, [0x1290], 'int'),
	('Hunting Log - Research Level - Dodogama', gSaveMon, [0x1294], 'int'),
	('Hunting Log - Research Level - Kulve Taroth', gSaveMon, [0x1298], 'int'),
	('Hunting Log - Research Level - Bazelgeuse', gSaveMon, [0x129C], 'int'),
	('Hunting Log - Research Level - Apceros', gSaveMon, [0x12A0], 'int'),
	('Hunting Log - Research Level - Kelbi (male)', gSaveMon, [0x12A4], 'int'),
	('Hunting Log - Research Level - Kelbi (female)', gSaveMon, [0x12A8], 'int'),
	('Hunting Log - Research Level - Hornetaur', gSaveMon, [0x12AC], 'int'),
	('Hunting Log - Research Level - Vespoid', gSaveMon, [0x12B0], 'int'),
	('Hunting Log - Research Level - Mernos', gSaveMon, [0x12B4], 'int'),
	('Hunting Log - Research Level - Kestodon (female)', gSaveMon, [0x12B8], 'int'),
	('Hunting Log - Research Level - Raphinos', gSaveMon, [0x12BC], 'int'),
	('Hunting Log - Research Level - Shamos', gSaveMon, [0x12C0], 'int'),
	('Hunting Log - Research Level - Barnos', gSaveMon, [0x12C4], 'int'),
	('Hunting Log - Research Level - Girros', gSaveMon, [0x12C8], 'int'),
	('Hunting Log - Research Level - Ancient Leshen', gSaveMon, [0x12CC], 'int'),
	('Hunting Log - Research Level - Gastodon', gSaveMon, [0x12D0], 'int'),
	('Hunting Log - Research Level - Noios', gSaveMon, [0x12D4], 'int'),
	('Hunting Log - Research Level - Gajalaka', gSaveMon, [0x12E0], 'int'),
	('Hunting Log - Research Level - Tigrex', gSaveMon, [0x12F4], 'int'),
	('Hunting Log - Research Level - Nargacuga', gSaveMon, [0x12F8], 'int'),
	('Hunting Log - Research Level - Barioth', gSaveMon, [0x12FC], 'int'),
	('Hunting Log - Research Level - Savage Deviljho', gSaveMon, [0x1300], 'int'),
	('Hunting Log - Research Level - Brachydios', gSaveMon, [0x1304], 'int'),
	('Hunting Log - Research Level - Glavenus', gSaveMon, [0x1308], 'int'),
	('Hunting Log - Research Level - Acidic Glavenus', gSaveMon, [0x130C], 'int'),
	('Hunting Log - Research Level - Fulgur Anjanath', gSaveMon, [0x1310], 'int'),
	('Hunting Log - Research Level - Coral Pukei-Pukei', gSaveMon, [0x1314], 'int'),
	('Hunting Log - Research Level - Ruiner Nergigante', gSaveMon, [0x1318], 'int'),
	('Hunting Log - Research Level - Viper Tobi-Kadachi', gSaveMon, [0x131C], 'int'),
	('Hunting Log - Research Level - Nightshade Paolumu', gSaveMon, [0x1320], 'int'),
	('Hunting Log - Research Level - Shrieking Legiana', gSaveMon, [0x1324], 'int'),
	('Hunting Log - Research Level - Ebony Odogaron', gSaveMon, [0x1328], 'int'),
	('Hunting Log - Research Level - Blackveil Vaal Hazak', gSaveMon, [0x132C], 'int'),
	('Hunting Log - Research Level - Seething Bazelgeuse', gSaveMon, [0x1330], 'int'),
	('Hunting Log - Research Level - Beotodus', gSaveMon, [0x1334], 'int'),
	('Hunting Log - Research Level - Banbaro', gSaveMon, [0x1338], 'int'),
	('Hunting Log - Research Level - Velkhana', gSaveMon, [0x133C], 'int'),
	('Hunting Log - Research Level - Namielle', gSaveMon, [0x1340], 'int'),
	('Hunting Log - Research Level - Shara Ishvalda', gSaveMon, [0x1344], 'int'),
	('Hunting Log - Research Level - Popo', gSaveMon, [0x1348], 'int'),
	('Hunting Log - Research Level - Anteka', gSaveMon, [0x134C], 'int'),
	('Hunting Log - Research Level - Wulg', gSaveMon, [0x1350], 'int'),
	('Hunting Log - Research Level - Cortos', gSaveMon, [0x1354], 'int'),
	('Hunting Log - Research Level - Boaboa', gSaveMon, [0x1358], 'int'),
	('Hunting Log - Research Level - Alatreon', gSaveMon, [0x135C], 'int'),
	('Hunting Log - Research Level - Gold Rathian', gSaveMon, [0x1360], 'int'),
	('Hunting Log - Research Level - Silver Rathalos', gSaveMon, [0x1364], 'int'),
	('Hunting Log - Research Level - Yian Garuga', gSaveMon, [0x1368], 'int'),
	('Hunting Log - Research Level - Rajang', gSaveMon, [0x136C], 'int'),
	('Hunting Log - Research Level - Furious Rajang', gSaveMon, [0x1370], 'int'),
	('Hunting Log - Research Level - Brute Tigrex', gSaveMon, [0x1374], 'int'),
	('Hunting Log - Research Level - Zinogre', gSaveMon, [0x1378], 'int'),
	('Hunting Log - Research Level - Stygian Zinogre', gSaveMon, [0x137C], 'int'),
	('Hunting Log - Research Level - Raging Brachydios', gSaveMon, [0x1380], 'int'),
	('Hunting Log - Research Level - Safi\'jiiva', gSaveMon, [0x1384], 'int'),
	('Hunting Log - Research Level - Scarred Yian Garuga', gSaveMon, [0x1388], 'int'),
	('Hunting Log - Research Level - Frostfang Barioth', gSaveMon, [0x138C], 'int'),
	('Hunting Log - Research Level - Fatalis', gSaveMon, [0x1390], 'int'),
	('Weapon Usage - High Rank - Great Sword', gSaveWeap, [0x0], 'int'),
	('Weapon Usage - High Rank - Sword & Shield', gSaveWeap, [0x4], 'int'),
	('Weapon Usage - High Rank - Dual Blades', gSaveWeap, [0x8], 'int'),
	('Weapon Usage - High Rank - Long Sword', gSaveWeap, [0xC], 'int'),
	('Weapon Usage - High Rank - Hammer', gSaveWeap, [0x10], 'int'),
	('Weapon Usage - High Rank - Hunting Horn', gSaveWeap, [0x14], 'int'),
	('Weapon Usage - High Rank - Lance', gSaveWeap, [0x18], 'int'),
	('Weapon Usage - High Rank - Gunlance', gSaveWeap, [0x1C], 'int'),
	('Weapon Usage - High Rank - Switch Axe', gSaveWeap, [0x20], 'int'),
	('Weapon Usage - High Rank - Charge Blade', gSaveWeap, [0x24], 'int'),
	('Weapon Usage - High Rank - Insect Glaive', gSaveWeap, [0x28], 'int'),
	('Weapon Usage - High Rank - Bow', gSaveWeap, [0x2C], 'int'),
	('Weapon Usage - High Rank - Heavy Bowgun', gSaveWeap, [0x30], 'int'),
	('Weapon Usage - High Rank - Light Bowgun', gSaveWeap, [0x34], 'int'),
	('Weapon Usage - Low Rank - Great Sword', gSaveWeap, [0x38], 'int'),
	('Weapon Usage - Low Rank - Sword & Shield', gSaveWeap, [0x3C], 'int'),
	('Weapon Usage - Low Rank - Dual Blades', gSaveWeap, [0x40], 'int'),
	('Weapon Usage - Low Rank - Long Sword', gSaveWeap, [0x44], 'int'),
	('Weapon Usage - Low Rank - Hammer', gSaveWeap, [0x48], 'int'),
	('Weapon Usage - Low Rank - Hunting Horn', gSaveWeap, [0x4C], 'int'),
	('Weapon Usage - Low Rank - Lance', gSaveWeap, [0x50], 'int'),
	('Weapon Usage - Low Rank - Gunlance', gSaveWeap, [0x54], 'int'),
	('Weapon Usage - Low Rank - Switch Axe', gSaveWeap, [0x58], 'int'),
	('Weapon Usage - Low Rank - Charge Blade', gSaveWeap, [0x5C], 'int'),
	('Weapon Usage - Low Rank - Insect Glaive', gSaveWeap, [0x60], 'int'),
	('Weapon Usage - Low Rank - Bow', gSaveWeap, [0x64], 'int'),
	('Weapon Usage - Low Rank - Heavy Bowgun', gSaveWeap, [0x68], 'int'),
	('Weapon Usage - Low Rank - Light Bowgun', gSaveWeap, [0x6C], 'int'),
	('Weapon Usage - Investigations - Great Sword', gSaveWeap, [0x70], 'int'),
	('Weapon Usage - Investigations - Sword & Shield', gSaveWeap, [0x74], 'int'),
	('Weapon Usage - Investigations - Dual Blades', gSaveWeap, [0x78], 'int'),
	('Weapon Usage - Investigations - Long Sword', gSaveWeap, [0x7C], 'int'),
	('Weapon Usage - Investigations - Hammer', gSaveWeap, [0x80], 'int'),
	('Weapon Usage - Investigations - Hunting Horn', gSaveWeap, [0x84], 'int'),
	('Weapon Usage - Investigations - Lance', gSaveWeap, [0x88], 'int'),
	('Weapon Usage - Investigations - Gunlance', gSaveWeap, [0x8C], 'int'),
	('Weapon Usage - Investigations - Switch Axe', gSaveWeap, [0x90], 'int'),
	('Weapon Usage - Investigations - Charge Blade', gSaveWeap, [0x94], 'int'),
	('Weapon Usage - Investigations - Insect Glaive', gSaveWeap, [0x98], 'int'),
	('Weapon Usage - Investigations - Bow', gSaveWeap, [0x9C], 'int'),
	('Weapon Usage - Investigations - Heavy Bowgun', gSaveWeap, [0xA0], 'int'),
	('Weapon Usage - Investigations - Light Bowgun', gSaveWeap, [0xA4], 'int'),
	('Weapon Usage - Master Rank - Great Sword', gSaveWeap, [0xA8], 'int'),
	('Weapon Usage - Master Rank - Sword & Shield', gSaveWeap, [0xAC], 'int'),
	('Weapon Usage - Master Rank - Dual Blades', gSaveWeap, [0xB0], 'int'),
	('Weapon Usage - Master Rank - Long Sword', gSaveWeap, [0xB4], 'int'),
	('Weapon Usage - Master Rank - Hammer', gSaveWeap, [0xB8], 'int'),
	('Weapon Usage - Master Rank - Hunting Horn', gSaveWeap, [0xBC], 'int'),
	('Weapon Usage - Master Rank - Lance', gSaveWeap, [0xC0], 'int'),
	('Weapon Usage - Master Rank - Gunlance', gSaveWeap, [0xC4], 'int'),
	('Weapon Usage - Master Rank - Switch Axe', gSaveWeap, [0xC8], 'int'),
	('Weapon Usage - Master Rank - Charge Blade', gSaveWeap, [0xCC], 'int'),
	('Weapon Usage - Master Rank - Insect Glaive', gSaveWeap, [0xD0], 'int'),
	('Weapon Usage - Master Rank - Bow', gSaveWeap, [0xD4], 'int'),
	('Weapon Usage - Master Rank - Heavy Bowgun', gSaveWeap, [0xD8], 'int'),
	('Weapon Usage - Master Rank - Light Bowgun', gSaveWeap, [0xDC], 'int'),
	('Weapon Usage - Guiding Lands - Great Sword', gSaveWeap, [0xE0], 'int'),
	('Weapon Usage - Guiding Lands - Sword & Shield', gSaveWeap, [0xE4], 'int'),
	('Weapon Usage - Guiding Lands - Dual Blades', gSaveWeap, [0xE8], 'int'),
	('Weapon Usage - Guiding Lands - Long Sword', gSaveWeap, [0xEC], 'int'),
	('Weapon Usage - Guiding Lands - Hammer', gSaveWeap, [0xF0], 'int'),
	('Weapon Usage - Guiding Lands - Hunting Horn', gSaveWeap, [0xF4], 'int'),
	('Weapon Usage - Guiding Lands - Lance', gSaveWeap, [0xF8], 'int'),
	('Weapon Usage - Guiding Lands - Gunlance', gSaveWeap, [0xFC], 'int'),
	('Weapon Usage - Guiding Lands - Switch Axe', gSaveWeap, [0x100], 'int'),
	('Weapon Usage - Guiding Lands - Charge Blade', gSaveWeap, [0x104], 'int'),
	('Weapon Usage - Guiding Lands - Insect Glaive', gSaveWeap, [0x108], 'int'),
	('Weapon Usage - Guiding Lands - Bow', gSaveWeap, [0x10C], 'int'),
	('Weapon Usage - Guiding Lands - Heavy Bowgun', gSaveWeap, [0x110], 'int'),
	('Weapon Usage - Guiding Lands - Light Bowgun', gSaveWeap, [0x114], 'int'),
]


for pointer in pointers:
	read_pointer_var(*pointer)

df = pd.DataFrame.from_records(data, index=['Value']).T
df.reset_index(inplace=True, names='Variable')
df.to_csv(r'processing/raw_iceborne.tsv', sep='\t', index=False)